name: throwable_lints
description: A custom lint package to enforce checked-exceptions for Dart using analysis_server_plugin.
version: 1.0.0-alpha.1
repository: https://github.com/kevin-sakemaer/throwable

resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  analysis_server_plugin: ^0.3.9
  analyzer: ^10.0.0
  analyzer_plugin: ^0.14.4
  throwable: ^1.0.0-alpha.1

dev_dependencies:
  analyzer_testing: ^0.2.1
  test: ^1.24.0
  test_reflective_loader: ^0.4.0
